### ISSUE TITLE
AddressSanitizer: odr-violation

### ISSUE THREAD

**Issue by ishitatsuyuki** [alexcrichton/libz-sys#16]
Just came across with this failure when trying ASan:

```
   Compiling libz-sys v1.0.13 (file:///tmp/libz-sys)
error: failed to run custom build command for `libz-sys v1.0.13 (file:///tmp/libz-sys)`
process didn't exit successfully: `/tmp/libz-sys/target/debug/build/libz-sys-adcfdad3f52dba5a/build-script-build` (exit code: 1)
--- stderr
=================================================================
==3839==ERROR: AddressSanitizer: odr-violation (0x5604022c8b20):
  [1] size=0 'ref.x' pkg_config.rs
  [2] size=0 'ref.d' build_script_build.rs
These globals were registered at these points:
  [1]:
    #0 0x5604021f2130 in __asan_register_globals.part.11 /build/src/rust/src/compiler-rt/lib/asan/asan_globals.cc:338
    #1 0x5604020a3bad in asan.module_ctor (/tmp/libz-sys/target/debug/build/libz-sys-adcfdad3f52dba5a/build-script-build+0xc0bad)

  [2]:
    #0 0x5604021f2130 in __asan_register_globals.part.11 /build/src/rust/src/compiler-rt/lib/asan/asan_globals.cc:338
    #1 0x56040202420d in asan.module_ctor (/tmp/libz-sys/target/debug/build/libz-sys-adcfdad3f52dba5a/build-script-build+0x4120d)

==3839==HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_odr_violation=0
SUMMARY: AddressSanitizer: odr-violation: global 'ref.x' at pkg_config.rs
==3839==ABORTING
```

I'm not sure if this can be ignored.

**Comment by ishitatsuyuki** [comment]
Since this is about 0 sized things, I'm moving this to compiler repo.
