### ISSUE TITLE
build fail on windows

### ISSUE THREAD

**Issue by void-dragon** [alexcrichton/libz-sys#34]
compiling libz on windows fails.

rust toolchain: stable-x86_64-pc-windows-gnu
gcc: nuwen mingw

the libz.a from mingw is not used, which seems legit. but i do not understand why the build from scratch fails.

it tells at the end "flag -z not usable at this position" but, i dont know what to do about it.

```
Compiling libz-sys v1.0.18
error: failed to run custom build command for `libz-sy
process didn't exit successfully: `E:\workspace\js\tar
--- stdout
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
HOST_CC = None
CC = None
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "make" "-f" "win32/Makefile.gcc" "install" "p
ibz-sys-e497dc2b35d3ad8c/out/include" "LIBRARY_PATH=/E
b35d3ad8c/out/bin"


command did not execute successfully, got: exit code:



--- stderr
"-z" kann syntaktisch an dieser Stelle nicht verarbeit
make: *** [win32/Makefile.gcc:128: install] Error 255
```

**Comment by alexcrichton** [comment]
Thanks for the report! It looks like that error message may be cut off though? Is there other bits that it printed out?

**Comment by void-dragon** [comment]
no, unfortunately thats everything

**Comment by alexcrichton** [comment]
Sorry I'm not sure what's going on in that case :(

**Comment by Jake-Shadle** [comment]
Here's the output on my machine for what I assume is the same error.

```
   Compiling libz-sys v1.0.18
error: failed to run custom build command for `libz-sys v1.0.18`
process didn't exit successfully: `D:\git\freon\target\debug\build\libz-sys-7dca18029d9999c0\build-script-build` (exit code: 1)
--- stdout
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
HOST_CC = None
CC = None
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "make" "-f" "win32/Makefile.gcc" "install" "prefix=/D/git/freon/target/debug/build/libz-sys-d7dc2486ddfcdf23/out" "IMPLIB=" "INCLUDE_PATH=/D/git/freon/target/debug/build/libz-sys-d7dc2486ddfcdf23/out/include" "LIBRARY_PATH=/D/git/freon/target/debug/build/libz-sys-d7dc2486ddfcdf23/out/lib" "BINARY_PATH=/D/git/freon/target/debug/build/libz-sys-d7dc2486ddfcdf23/out/bin"
gcc  -O3 -Wall -c -o adler32.o adler32.c


command did not execute successfully, got: exit code: 2



--- stderr
process_begin: CreateProcess(NULL, gcc -O3 -Wall -c -o adler32.o adler32.c, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [adler32.o] Fel 2
```

It seems the makefile is assuming that gcc is in PATH, which I guess is a fair assumption in most cases.

**Comment by Pzixel** [comment]
```bat
if test -z "" -o -z "a"; then echo "" fi
```

it's not valid bat code.

**Comment by Pzixel** [comment]
I replaced this part with:

```batch
@if "$(DESTDIR)$(INCLUDE_PATH)" == ""; then \
	echo INCLUDE_PATH must be specified; \
	exit 1; \
fi
@if "$(DESTDIR)$(LIBRARY_PATH)" == ""; then \
	echo LIBRARY_PATH must be specified; \
	exit 1; \
fi
@if "$(DESTDIR)$(BINARY_PATH)" == ""; then \
	echo BINARY_PATH must be specified; \
	exit 1; \
fi
```

But now it fails to compile:

```ps
PS C:\Users\Alex\CLionProjects\untitled3\target\debug\build\libz-sys-26d039a019ce367e> .\build-script-build.exe
cargo:rerun-if-env-changed=LIBZ_SYS_STATIC
cargo:rerun-if-changed=build.rs
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', libcore\result.rs:945:5
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at libstd\sys\windows\backtrace/mod.rs:65
   1: std::sys_common::backtrace::print
             at libstd\sys_common/backtrace.rs:71
             at libstd\sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   6: rust_begin_unwind
             at libstd/panicking.rs:328
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   8: core::result::unwrap_failed
             at C:\projects\rust\src\libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at C:\projects\rust\src\libcore/result.rs:782
  10: build_script_build::main
             at C:\Users\Alex\.cargo\git\checkouts\libz-sys-4a01808fbc1b1031\8eb6f9e/build.rs:24
  11: std::rt::lang_start::{{closure}}
             at C:\projects\rust\src\libstd/rt.rs:74
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  13: _rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  14: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  15: std::rt::lang_start
             at C:\projects\rust\src\libstd/rt.rs:74
  16: main
  17: _tmainCRTStartup
  18: mainCRTStartup
  19: unit_addrs_search
  20: unit_addrs_search
```

**Comment by alexcrichton** [comment]
I've retooled the build in https://github.com/alexcrichton/libz-sys/pull/40, so this should be fixed now

**Comment by Pzixel** [comment]
It more looks like "let's not support gnu-windows at all" :)
